# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AddItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, category: str=None, food_item_name: str=None, quantity: int=None, price: int=None, eta: int=None, description: str=None):  # noqa: E501
        """AddItem - a model defined in Swagger

        :param category: The category of this AddItem.  # noqa: E501
        :type category: str
        :param food_item_name: The food_item_name of this AddItem.  # noqa: E501
        :type food_item_name: str
        :param quantity: The quantity of this AddItem.  # noqa: E501
        :type quantity: int
        :param price: The price of this AddItem.  # noqa: E501
        :type price: int
        :param eta: The eta of this AddItem.  # noqa: E501
        :type eta: int
        :param description: The description of this AddItem.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'category': str,
            'food_item_name': str,
            'quantity': int,
            'price': int,
            'eta': int,
            'description': str
        }

        self.attribute_map = {
            'category': 'category',
            'food_item_name': 'food_item_name',
            'quantity': 'quantity',
            'price': 'price',
            'eta': 'ETA',
            'description': 'description'
        }
        self._category = category
        self._food_item_name = food_item_name
        self._quantity = quantity
        self._price = price
        self._eta = eta
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'AddItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The add_item of this AddItem.  # noqa: E501
        :rtype: AddItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this AddItem.


        :return: The category of this AddItem.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this AddItem.


        :param category: The category of this AddItem.
        :type category: str
        """

        self._category = category

    @property
    def food_item_name(self) -> str:
        """Gets the food_item_name of this AddItem.


        :return: The food_item_name of this AddItem.
        :rtype: str
        """
        return self._food_item_name

    @food_item_name.setter
    def food_item_name(self, food_item_name: str):
        """Sets the food_item_name of this AddItem.


        :param food_item_name: The food_item_name of this AddItem.
        :type food_item_name: str
        """

        self._food_item_name = food_item_name

    @property
    def quantity(self) -> int:
        """Gets the quantity of this AddItem.


        :return: The quantity of this AddItem.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this AddItem.


        :param quantity: The quantity of this AddItem.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def price(self) -> int:
        """Gets the price of this AddItem.


        :return: The price of this AddItem.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price: int):
        """Sets the price of this AddItem.


        :param price: The price of this AddItem.
        :type price: int
        """

        self._price = price

    @property
    def eta(self) -> int:
        """Gets the eta of this AddItem.


        :return: The eta of this AddItem.
        :rtype: int
        """
        return self._eta

    @eta.setter
    def eta(self, eta: int):
        """Sets the eta of this AddItem.


        :param eta: The eta of this AddItem.
        :type eta: int
        """

        self._eta = eta

    @property
    def description(self) -> str:
        """Gets the description of this AddItem.


        :return: The description of this AddItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this AddItem.


        :param description: The description of this AddItem.
        :type description: str
        """

        self._description = description
